# Generated by Django 5.1.15 on 2026-09-07 19:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_user_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date')),
                ('duration_minutes', models.PositiveSmallIntegerField(verbose_name='Durée (minutes)')),
                ('motif', models.CharField(choices=[('TRANSPORT', 'Transport'), ('FAMILIAL', 'Raison familiale'), ('MEDICAL', 'Raison médicale'), ('ADMINISTRATIF', 'Démarche administrative'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Motif')),
                ('motif_detail', models.CharField(blank=True, max_length=255, verbose_name='Précision du motif')),
                ('justification', models.TextField(blank=True, help_text="Texte soumis par l'élève ou son représentant légal.", max_length=1000, verbose_name='Justification')),
                ('justification_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Justification soumise le')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de validation'), ('JUSTIFIED', 'Justifié'), ('UNJUSTIFIED', 'Non justifié')], db_index=True, default='PENDING', max_length=15, verbose_name='Validation')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retards_declares', to=settings.AUTH_USER_MODEL, verbose_name='Déclaré par')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retards', to='users.studentprofile', verbose_name='Élève')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retards_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Retard',
                'verbose_name_plural': 'Retards',
                'ordering': ('-date', '-created_at'),
                'indexes': [models.Index(fields=['date'], name='vie_scolair_date_ab060a_idx'), models.Index(fields=['status'], name='vie_scolair_status_09907f_idx')],
            },
        ),
    ]
