# Generated by Django 5.1.15 on 2026-09-08 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='bcc_recipients',
            field=models.ManyToManyField(blank=True, related_name='bcc_messages', to=settings.AUTH_USER_MODEL, verbose_name='Copie cachée'),
        ),
        migrations.AddField(
            model_name='message',
            name='cc_recipients',
            field=models.ManyToManyField(blank=True, related_name='cc_messages', to=settings.AUTH_USER_MODEL, verbose_name='Copie'),
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='message',
            name='to_recipients',
            field=models.ManyToManyField(blank=True, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinataires'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation'),
        ),
    ]
