# Generated by Django 5.1.15 on 2026-09-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('LATE', 'En retard'), ('EXCUSED', 'Justifié')], default='PRESENT', max_length=10)),
                ('minutes_late', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-recorded_at',),
            },
        ),
    ]
