# Generated by Django 5.1 on 2026-09-07 18:00
#
# Ajoute les champs `justified` / `justification_reason` sur AttendanceRecord
# ainsi que le modèle `AbsenceJustification` (justifications soumises par les
# parents et validées par les enseignants).
#
# Aucune donnée existante n'est perdue : les nouveaux champs ont une valeur
# par défaut compatible avec les enregistrements déjà créés.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_initial"),
        ("users", "0004_alter_user_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceJustification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(max_length=1000, verbose_name="Justification")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuvée"),
                            ("REJECTED", "Rejetée"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Soumis le"),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="justifications",
                        to="attendance.attendancerecord",
                        verbose_name="Absence concernée",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_justifications",
                        to="users.user",
                        verbose_name="Soumis par",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_justifications",
                        to="users.user",
                        verbose_name="Validé par",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Validé le"),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Justification d'absence",
                "verbose_name_plural": "Justifications d'absences",
            },
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="justified",
            field=models.BooleanField(default=False, verbose_name="Justifié"),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="justification_reason",
            field=models.TextField(blank=True, max_length=1000, verbose_name="Motif de la justification"),
        ),
    ]